import { Main } from "./styles";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: JSX.Element }) {
  return (
    <main className="grid items-center justify-center h-full w-full">
      {children}
    </main>
  );
}
